# Generated by Django 5.2.8 on 2025-11-13 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='ServiceStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('appointment_count', models.IntegerField(default=0, verbose_name='Количество записей')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfc_app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Статистика услуги',
                'verbose_name_plural': 'Статистика услуг',
            },
        ),
    ]
